#include "ddr_params_creator.h"

int main(int argc, char *argv[])
{
	int i;
	FILE *fp = fopen(argv[1], "w+");

	if(!fp)
		perror("failed to open\n");

	/* add header*/
	fprintf(fp, "/*\n");
	fprintf(fp, " * DO NOT MODIFY.\n");
	fprintf(fp, " *\n");
	fprintf(fp, " * This file was generated by ddr_params_creator\n");
	fprintf(fp, " *\n");
	fprintf(fp, " */\n");
	fprintf(fp, "\n");

	fprintf(fp, "#ifndef __DDR_REG_VALUES_H__\n");
	fprintf(fp, "#define __DDR_REG_VALUES_H__\n\n");


	for(i = 2; i < argc; i++) {

		fprintf(fp, "#include <%s> \n", argv[i]);
	}

	fprintf(fp, "extern unsigned int DDRC_CFG_VALUE;	\n");
	fprintf(fp, "extern unsigned int DDRC_CTRL_VALUE;	\n");
	fprintf(fp, "extern unsigned int DDRC_DLMR_VALUE;	\n");
	fprintf(fp, "extern unsigned int DDRC_DDLP_VALUE;	\n");
	fprintf(fp, "extern unsigned int DDRC_MMAP0_VALUE;	\n");
	fprintf(fp, "extern unsigned int DDRC_MMAP1_VALUE;	\n");
	fprintf(fp, "extern unsigned int DDRC_REFCNT_VALUE;	\n");
	fprintf(fp, "extern unsigned int DDRC_TIMING1_VALUE;	\n");
	fprintf(fp, "extern unsigned int DDRC_TIMING2_VALUE;	\n");
	fprintf(fp, "extern unsigned int DDRC_TIMING3_VALUE;	\n");
	fprintf(fp, "extern unsigned int DDRC_TIMING4_VALUE;	\n");
	fprintf(fp, "extern unsigned int DDRC_TIMING5_VALUE;	\n");
	fprintf(fp, "extern unsigned int DDRC_TIMING6_VALUE;	\n");
	fprintf(fp, "extern unsigned int DDRC_AUTOSR_EN_VALUE;	\n");

#ifndef CONFIG_DDR_INNOPHY
	fprintf(fp, "extern unsigned int DDRP_DCR_VALUE;	\n");
	fprintf(fp, "extern unsigned int DDRP_MR0_VALUE;	\n");
	fprintf(fp, "extern unsigned int DDRP_MR1_VALUE;	\n");
	fprintf(fp, "extern unsigned int DDRP_MR2_VALUE;	\n");
	fprintf(fp, "extern unsigned int DDRP_MR3_VALUE;	\n");
	fprintf(fp, "extern unsigned int DDRP_PTR0_VALUE;	\n");
	fprintf(fp, "extern unsigned int DDRP_PTR1_VALUE;	\n");
	fprintf(fp, "extern unsigned int DDRP_PTR2_VALUE;	\n");
	fprintf(fp, "extern unsigned int DDRP_DTPR0_VALUE;	\n");
	fprintf(fp, "extern unsigned int DDRP_DTPR1_VALUE;	\n");
	fprintf(fp, "extern unsigned int DDRP_DTPR2_VALUE;	\n");
	fprintf(fp, "extern unsigned int DDRP_PGCR_VALUE;	\n");
	fprintf(fp, "extern unsigned int DDRP_ODTCR_VALUE;	\n");
	fprintf(fp, "extern unsigned int DDRP_DX0GCR_VALUE;	\n");
	fprintf(fp, "extern unsigned int DDRP_DX1GCR_VALUE;	\n");
	fprintf(fp, "extern unsigned int DDRP_DX2GCR_VALUE;	\n");
	fprintf(fp, "extern unsigned int DDRP_DX3GCR_VALUE;	\n");
	fprintf(fp, "extern unsigned int DDRP_ZQNCR1_VALUE;	\n");
	fprintf(fp, "extern unsigned int DDRP_IMPANDCE_ARRAY[2];\n");
	fprintf(fp, "extern unsigned int DDRP_ODT_IMPANDCE_ARRAY[2];\n");
	fprintf(fp, "extern unsigned char DDRP_RZQ_TABLE[32];\n");
#else
	fprintf(fp, "extern unsigned int DDRP_MEMCFG_VALUE;\n");
	fprintf(fp, "extern unsigned int DDRP_CL_VALUE; \n");
	fprintf(fp, "extern unsigned int DDRP_CWL_VALUE;\n");
	fprintf(fp, "extern unsigned int DDR_MR0_VALUE;\n");
	fprintf(fp, "extern unsigned int DDR_MR1_VALUE;\n");
	fprintf(fp, "extern unsigned int DDR_MR2_VALUE;\n");
	fprintf(fp, "extern unsigned int DDR_MR3_VALUE;\n");
	fprintf(fp, "extern unsigned int DDR_MR10_VALUE;\n");
	fprintf(fp, "extern unsigned int DDR_MR63_VALUE;\n");
#endif
	fprintf(fp, "extern unsigned int DDR_CHIP_0_SIZE;\n");
	fprintf(fp, "extern unsigned int DDR_CHIP_1_SIZE;\n");
	fprintf(fp, "extern unsigned int REMMAP_ARRAY[5];\n");

	/*add ender*/
	fprintf(fp, "\n#endif /* __DDR_REG_VALUES_H__ */\n");

	close(fp);

	return 0;
}
