obj-y := beagleb2.o
obj-y += ../../ti/beagle/led.o

# extended commands

ifndef CONFIG_SPL_BUILD
obj-y += ../letux-gta04-b2/COM37H3M05DTC.o
obj-y += ../letux-gta04/status.o
obj-y += ../letux-gta04/shutdown.o
obj-y += ../letux-gta04/commands.o
obj-y += ../letux-gta04/ulpi-phy.o
obj-y += ../letux-gta04/twl4030-additions.o
obj-y += ../letux-gta04/backlight.o
obj-y += ../letux-gta04/tsc2007.o
obj-y += ../letux-gta04/dssfb.o
obj-y += ../letux-gta04/gps.o
obj-y += ../letux-gta04/systest.o
obj-y += ../letux-gta04-b2/trf7960.o
endif
