
add_custom_command(OUTPUT HOST_TOOLS_BUILD.${OUTPUT}
	COMMAND ${HOSTCC} ${HOSTCFLAGS} -o ${OUTPUT}${EXEC_EXTENTION_SUFFIX} ${SOURCE} && strip ${OUTPUT}${EXEC_EXTENTION_SUFFIX}
	BYPRODUCTS ${OUTPUT}${EXEC_EXTENTION_SUFFIX}
	DEPENDS ${SOURCE}
	COMMENT "Generating ${OUTPUT}"
	VERBATIM
	)

