obj-y := beagleb4.o
obj-y += ../../ti/beagle/led.o

# extended commands

ifndef CONFIG_SPL_BUILD
obj-y += ../letux-gta04-b4/LQ050W1LC1B.o
obj-y += ../letux-gta04/jbt6k74.o
obj-y += ../letux-gta04/status.o
obj-y += ../letux-gta04/shutdown.o
obj-y += ../letux-gta04/commands.o
obj-y += ../letux-gta04/ulpi-phy.o
obj-y += ../letux-gta04/twl4030-additions.o
obj-y += ../letux-gta04/backlight.o
obj-y += ../letux-gta04/tsc2007.o
obj-y += ../letux-gta04/dssfb.o
obj-y += ../letux-gta04/gps.o
obj-y += ../letux-gta04/systest.o
endif
