obj-y := gta04.o

ifndef CONFIG_SPL_BUILD
obj-y += TD028TTEC1.o
obj-y += jbt6k74.o
obj-y += status.o
obj-y += shutdown.o
obj-y += commands.o
obj-y += ulpi-phy.o
obj-y += twl4030-additions.o
obj-y += backlight.o
obj-y += tsc2007.o
obj-y += dssfb.o
obj-y += gps.o
obj-y += systest.o
obj-y += i2c1-fix.o
endif
