#define MUX_BEAGLE_HYBRID() \
MUX_VAL(CP(MMC2_CLK),		(IEN  | PTU | EN  | M1)) /*GPIO_130 -> MCSPI3-CLK*/\
MUX_VAL(CP(MMC2_CMD),		(IEN  | PTU | EN  | M1)) /*GPIO_131 -> MCSPI3-SIMO*/\
MUX_VAL(CP(MMC2_DAT0),		(IEN  | PTU | EN  | M1)) /*GPIO_132 -> MCSPI3-SOMI*/\
MUX_VAL(CP(MMC2_DAT1),		(IEN  | PTU | EN  | M4)) /*GPIO_133 -> UART3-RX (software)*/\
MUX_VAL(CP(MMC2_DAT2),		(IEN  | PTU | EN  | M4)) /*GPIO_134 -> UART3-TX (software)*/\
MUX_VAL(CP(MMC2_DAT3),		(IEN  | PTU | EN  | M1)) /*GPIO_135 -> MCSPI3-CS0*/\
MUX_VAL(CP(MMC2_DAT4),		(IEN  | PTD | EN  | M4)) /*GPIO_136 - AUX */\
MUX_VAL(CP(MMC2_DAT5),		(IEN  | PTU | EN  | M4)) /*GPIO_137 - POWER */\
MUX_VAL(CP(MMC2_DAT6),		(IEN  | PTU | DIS  | M4)) /*GPIO_138 - UART3-RTS (software) */\
MUX_VAL(CP(MMC2_DAT7),		(IEN  | PTU | EN  | M4)) /*GPIO_139 - UART3-CTS (software) */\
MUX_VAL(CP(MCBSP1_CLKR),	(IDIS | PTD | DIS | M4)) /*GPIO_156 - KEYIRQ*/\
MUX_VAL(CP(MCBSP1_FSR),		(IEN  | PTU | EN  | M4)) /*GPIO_157 - PENIRQ */\
MUX_VAL(CP(MCBSP1_DX),		(IDIS | PTD | EN  | M0)) /*GPIO_158 - McBSP1-DX */\
MUX_VAL(CP(MCBSP1_DR),		(IEN  | PTU | DIS | M0)) /*GPIO_159 - McBSP1-DR */\
MUX_VAL(CP(MCBSP_CLKS),		(IEN  | PTU | DIS | M0)) /*McBSP_CLKS*/\
MUX_VAL(CP(MCBSP1_FSX),		(IDIS | PTU | EN  | M0)) /*GPIO_161 - McBSP1-FSX */\
MUX_VAL(CP(MCBSP1_CLKX),	(IDIS | PTD | EN  | M0)) /*GPIO_162 - McBSP1-CLKX */

// should we mux GPIO 143/44/45/46 for UART2 and/or GPT/PWM?